# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YearbookAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Student's Yearbook Answer",
                'ordering': ['yearbook_question', 'updated_at'],
                'verbose_name_plural': "Student's Yearbook Answers",
            },
        ),
        migrations.CreateModel(
            name='YearbookQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('hint', models.CharField(blank=True, help_text='Give a hint on how to answer the question. (optional)', max_length=200, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yearbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Yearbook')),
            ],
            options={
                'permissions': (('can create yearbook question', 'Create a yearbook question'),),
                'ordering': ['publish', 'question_text'],
            },
        ),
        migrations.AddField(
            model_name='yearbookanswer',
            name='yearbook_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.YearbookQuestion'),
        ),
    ]
