# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_text', models.CharField(help_text='Poll question to display', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the purpose of the poll (Optional)', null=True)),
                ('active', models.BooleanField(default=False, help_text='Weather or not the poll is currently open for voting.', verbose_name='Open for Vote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateField(verbose_name='Deadline for voting')),
            ],
            options={
                'ordering': ['active', '-end_at'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Poll')),
            ],
            options={
                'ordering': ['poll'],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, help_text='Date where the student voted on the poll')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PollChoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Poll')),
            ],
            options={
                'ordering': ['poll', '-submitted_date'],
            },
        ),
    ]
