# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_poll_pollchoice_pollresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Summary of the event')),
                ('dress_code', models.TextField(blank=True, help_text='Are there any dress codes to follow? (Optional)', null=True)),
                ('venue', models.CharField(help_text='Where the event is taking place', max_length=100)),
                ('start_at', models.DateTimeField(help_text='Starting date and time of the event')),
                ('end_at', models.DateTimeField(help_text='Ending date and time of the event')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Entrance Fee for the event. (Enter 0.00 if event is free)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False, help_text='Publish to make event visible to all students')),
            ],
            options={
                'ordering': ['-start_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Short description of the program')),
                ('start_at', models.TimeField(help_text='Starting time of the program')),
                ('end_at', models.TimeField(help_text='Ending time of the program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Event')),
            ],
            options={
                'ordering': ['event', '-start_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='pollresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
