# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20170930_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYearbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Do you have a nickname? (Optional)', max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('bio', models.TextField(help_text='Tell the world about yourself in less than 300 characters.', verbose_name='About yourself?')),
                ('quote', models.TextField(verbose_name='Your favorite quote or motto?')),
                ('thank_you_message', models.TextField(help_text='Take this opportunity to thank those who are special to you.', verbose_name='Who would like to thank?')),
                ('submit', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submit', '-submitted_date', 'student'],
            },
        ),
        migrations.RemoveField(
            model_name='yearbookanswer',
            name='yearbook_question',
        ),
        migrations.RemoveField(
            model_name='yearbookquestion',
            name='yearbook',
        ),
        migrations.RemoveField(
            model_name='yearbook',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='yearbook',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='yearbook',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='YearbookAnswer',
        ),
        migrations.DeleteModel(
            name='YearbookQuestion',
        ),
        migrations.AddField(
            model_name='studentyearbook',
            name='yearbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Yearbook'),
        ),
    ]
