# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170930_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentyearbook',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentyearbook',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentyearbook',
            name='thank_you_message',
            field=models.TextField(help_text='Take this opportunity to thank those who are special to you.', verbose_name='Who would you like to thank?'),
        ),
        migrations.AlterField(
            model_name='studentyearbook',
            name='yearbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Yearbook'),
        ),
    ]
