# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 03:14
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_studentyearbook_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentyearbook',
            name='photo',
            field=models.ImageField(default='uploads/no_photo.jpg', upload_to=dashboard.models.student_suit_path),
        ),
    ]
