# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 07:57
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_studentyearbook_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentyearbook',
            name='photo',
        ),
        migrations.AddField(
            model_name='studentyearbook',
            name='baby_photo',
            field=models.ImageField(default='/upload/no_photo.jpg', upload_to=dashboard.models.baby_photo_path, verbose_name='Baby photo'),
        ),
        migrations.AddField(
            model_name='studentyearbook',
            name='gown_photo',
            field=models.ImageField(default='/upload/no_photo.jpg', upload_to=dashboard.models.gown_photo_path),
        ),
        migrations.AddField(
            model_name='studentyearbook',
            name='suit_photo',
            field=models.ImageField(default='/upload/no_photo.jpg', upload_to=dashboard.models.suit_photo_path, verbose_name='Suit/Dress photo'),
        ),
    ]
