# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171003_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollResult',
            new_name='Vote',
        ),
    ]
