# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20171007_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['active', 'end_at']},
        ),
    ]
