# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 11:28
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20171007_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_datetime', 'title']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.event_photo_path),
        ),
    ]
