# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_studentevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentEvent',
            new_name='EventSubscription',
        ),
    ]
