# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20171013_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
    ]
