# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_profile_is_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='publish',
            field=models.BooleanField(default=False, help_text='Published polls can be viewed by all students'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether or not the poll is currently open for voting.', verbose_name='Open for Vote'),
        ),
    ]
