# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20171018_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['publish', 'active', 'end_at']},
        ),
    ]
